services:
  - type: web
    name: fl_backend
    env: node
    plan: free
    # repo: git@github.com:huan00/friday_laundry_backend.git
    buildCommand: npm install && npx sequelize-cli db:migrate
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_SECRET
        value: mysecretkey
      - key: SALT_ROUNDS
        value: 12
# services:
#   - type: web
#   name: fl_backend
#   env: node
#   # plan: standard
#   repo: git@github.com:huan00/friday_laundry_backend.git
#   buildCommand: npm install && npx sequelize-cli db:migrate
#   startCommand: npm start
#   envVars:
#     - key: postgres://friday_laundry_o0dv_user:llJtOtnL6KeoYKySvHT3gXiKnvlFhmb0@dpg-cg351sl269v3bp8gcuag-a/friday_laundry_o0dv
#     fromDatabase:
#       name: friday_laundry_o0dv
#       propperty: ''
#   - key: POOL_MODE
#       value: transaction
#     - key: SERVER_RESET_QUERY
#       value: DISCARD ALL
#     - key: MAX_CLIENT_CONN
#       value: 500
#     - key: DEFAULT_POOL_SIZE
#       value: 50

# databases:
#   - name: friday_laundry_o0dv
#     databaseName: friday_laundry_o0dv
#     user: friday_laundry_o0dv_user

databases:
  - name: friday_laundry
